import asyncio
import os
from pathlib import Path
import sys

# Configure UTF-8 encoding for Windows console to handle emojis safely
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except AttributeError:
        pass

# Add project root to sys.path
sys.path.append(os.path.abspath(os.path.dirname(__file__)))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "services/ai-brain")))

from omni_parser import scan_omni_directory, UniversalNode

async def generate_antigravity_map():
    print("🚀 [ANTIGRAVITY-MAP]: Starting project mapping for Antigravity...")
    
    base_dir = os.path.abspath(os.path.dirname(__file__))
    
    # Scan main directories
    scan_dirs = [
        os.path.join(base_dir, "core"),
        os.path.join(base_dir, "services"),
        os.path.join(base_dir, "intelligence"),
        os.path.join(base_dir, "scripts"),
    ]
    
    all_nodes = []
    for d in scan_dirs:
        if os.path.exists(d):
            print(f"🔍 [SCANNING]: {d}")
            nodes = await scan_omni_directory(d)
            all_nodes.extend(nodes)
            
    print(f"📊 [NODES-FOUND]: {len(all_nodes)} nodes identified.")
    
    # Generate Map File
    map_file = os.path.join(base_dir, "ANTIGRAVITY_MAP_GRAPH.md")
    
    content = [
        "# 🗺️ ANTIGRAVITY PROJECT MAP GRAPH",
        "**The Sovereign Architect's View of the JKAI Zenith Ecosystem**",
        "",
        "## 🏛️ CORE COMPONENTS",
        "| Category | Node | Path | Links |",
        "| :--- | :--- | :--- | :--- |"
    ]
    
    # Group by type
    by_type = {}
    for node in all_nodes:
        t = node.file_type
        if t not in by_type: by_type[t] = []
        by_type[t].append(node)
        
    for t, nodes in sorted(by_type.items()):
        for node in nodes[:20]: # Limit to 20 per type for brevity in the main map
            links = ", ".join(node.links_to[:5])
            content.append(f"| {t} | {node.name} | `{node.file}` | {links} |")
            
    content.append("\n## 🧬 NEURAL LINKS (SOP & PROTOCOLS)")
    # Extract protocols specifically
    protocols = [n for n in all_nodes if "protocol" in n.file.lower()]
    for p in protocols:
        content.append(f"- **{p.name}**: `{p.file}`")
        
    content.append("\n---")
    content.append("*Sovereign Property of Master LeeTrung. Generated by Antigravity AI for Personal Navigation.* 🏛️🦾🚀")
    
    with open(map_file, "w", encoding="utf-8") as f:
        f.write("\n".join(content))
        
    print(f"✅ [MAP-GENERATED]: {map_file}")

if __name__ == "__main__":
    asyncio.run(generate_antigravity_map())
