import os
import sys
import json
import asyncio
import time
import logging
from typing import List, Dict, Any

# [PATH-ALIGNMENT]: Tim duong dan goc cua project
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
if project_root not in sys.path:
    try:
    from core.utils.engine import engine
except ImportError:
    pass

from core.utils.engine import engine
from core.qdrant_client import qdrant_client
from core.utils.knowledge_brain import knowledge_brain

logger = logging.getLogger('NeuralArchitect')

class NeuralArchitect:
    """
    JKAI ZENITH: NEURAL ARCHITECT (#109)
    Capable of mapping, visualizing, and indexing project topologies.
    """
    def __init__(self, workspace_root: str = None):
        self.workspace_root = workspace_root or os.getcwd()
        self.topology_file = os.path.join(self.workspace_root, "ZENITH_TOPOLOGY.md")

    async def map_project(self, target_path: str = None, project_name: str = "Current Project", task_id: str = "arch_map"):
        """Quet va lap ban do kien truc du an."""
        path = target_path or self.workspace_root
        engine.publish_mission_log("ARCHITECT", f"[SCAN]: Dang bat dau tam soat dia hinh tai `{path}`...", task_id)
        
        files_found = []
        for root, dirs, files in os.walk(path):
            if any(x in root for x in [".git", "node_modules", "__pycache__", "venv", "dist", "build"]):
                continue
            for file in files:
                if file.endswith(('.py', '.js', '.json', '.md', '.ts', '.html', '.css')):
                    rel_path = os.path.relpath(os.path.join(root, file), path)
                    files_found.append(rel_path)
        
        analysis_prompt = (
            f"Danh sach cac tep tin trong du an `{project_name}`:\n"
            f"{json.dumps(files_found[:200], indent=2)}\n\n"
            f"Nhiem vu: Hay phan tich va xac dinh cac 'Node' chinh cua he thong.\n"
            f"1. Core Services.\n"
            f"2. Entry Points.\n"
            f"3. Data Flow.\n\n"
            f"Tra ve JSON: {{'nodes': [{{'id': str, 'label': str, 'type': str, 'description': str}}], 'edges': [{{'from': str, 'to': str, 'label': str}}]}}"
        )
        
        analysis_res = await engine.call_chat(
            messages=[{"role": "user", "content": analysis_prompt}],
            role="PLANNER",
            profile="ARCHITECT",
            json_mode=True,
            task_id=task_id
        )
        
        if not analysis_res:
            return "[ERR]: Khong the phan tich kien truc."

        mermaid_code = "graph TD\n"
        for edge in analysis_res.get('edges', []):
            mermaid_code += f"    {edge['from']} -->|\"{edge.get('label', '')}\"| {edge['to']}\n"
        
        topology_content = f"""# PROJECT TOPOLOGY: {project_name}
Generated by JKAI Neural Architect (#109)
Timestamp: {time.strftime('%Y-%m-%d %H:%M:%S')}

## Visual Architecture Map
```mermaid
{mermaid_code}
```

## Neural Nodes Registry
| Node ID | Type | Description |
| :--- | :--- | :--- |
"""
        for node in analysis_res.get('nodes', []):
            topology_content += f"| {node['id']} | {node['type']} | {node.get('description', '')} |\n"
            
            # Embed and index node
            embedding = await engine.get_embeddings(f"Node {node['id']} in {project_name}: {node.get('description', '')}")
            if embedding:
                await qdrant_client.upsert_intel(
                    text=f"Project Node: {node['id']}\nProject: {project_name}\nType: {node['type']}\nDesc: {node.get('description', '')}",
                    embedding=embedding,
                    metadata={"project": project_name, "node_id": node['id'], "type": "arch_node"},
                    collection="universal_graph"
                )

        with open(self.topology_file, "w", encoding="utf-8") as f:
            f.write(topology_content)
            
        return f"[SUCCESS]: Da lap xong ban do cho `{project_name}` tai ZENITH_TOPOLOGY.md"

async def run_skill(goal: str, task_id: str = "arch"):
    architect = NeuralArchitect()
    if "JKAI" in goal or "self" in goal.lower():
        return await architect.map_project(project_name="JKAI Zenith OS", task_id=task_id)
    return await architect.map_project(project_name="New Project", task_id=task_id)

if __name__ == "__main__":
    asyncio.run(run_skill("Map JKAI"))
