#!/usr/bin/env python3
"""
🛡️ Tool Schema Validator & Guardrail Enforcer for JKAI Zenith.
Intercepts LLM tool invocations, validates JSON structures against skill schemas,
performs parameter coercion, and formats clear error feedback for model self-correction.
"""

import json
import logging
from typing import Dict, Any, Tuple, Optional

logger = logging.getLogger("ToolSchemaValidator")


class ToolSchemaValidator:
    """
    Guardrail validator for tool arguments generated by LLM.
    """
    @staticmethod
    def parse_tool_call(raw_response: str) -> Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]]:
        """
        Parses JSON tool call from raw LLM text response.
        Supports format: ```json {"tool": "tool_name", "args": {...}} ```
        Returns: (tool_name, args_dict, error_message)
        """
        if not raw_response:
            return None, None, "Empty response from model."

        try:
            # Extract JSON block if enclosed in markdown
            text = raw_response.strip()
            if "```json" in text:
                text = text.split("```json")[1].split("```")[0].strip()
            elif "```" in text:
                text = text.split("```")[1].split("```")[0].strip()

            data = json.loads(text)
            if not isinstance(data, dict):
                return None, None, "Tool response must be a JSON object."

            tool_name = data.get("tool") or data.get("action") or data.get("name")
            args = data.get("args") or data.get("parameters") or data.get("input") or {}

            if not tool_name:
                return None, None, "Missing 'tool' or 'action' field in JSON."

            if not isinstance(args, dict):
                return None, None, f"Tool arguments for '{tool_name}' must be a dictionary/object."

            return tool_name, args, None

        except json.JSONDecodeError as e:
            return None, None, f"Invalid JSON syntax in tool call: {e}"

    @staticmethod
    def validate_and_coerce(tool_name: str, args: Dict[str, Any], schema: Dict[str, Any]) -> Tuple[Dict[str, Any], Optional[str]]:
        """
        Validates parameters against schema definitions and performs auto-coercion.
        """
        required_fields = schema.get("required", [])
        properties = schema.get("properties", {})

        coerced_args = {}

        # 1. Check required parameters
        for req in required_fields:
            if req not in args or args[req] is None:
                return {}, f"Missing required parameter '{req}' for tool '{tool_name}'."

        # 2. Validate and coerce types
        for key, value in args.items():
            if key not in properties:
                # Allowed or extra parameter
                coerced_args[key] = value
                continue

            expected_type = properties[key].get("type", "string")

            try:
                if expected_type == "integer":
                    coerced_args[key] = int(value)
                elif expected_type == "number" or expected_type == "float":
                    coerced_args[key] = float(value)
                elif expected_type == "boolean":
                    if isinstance(value, str):
                        coerced_args[key] = value.lower() in ["true", "1", "yes"]
                    else:
                        coerced_args[key] = bool(value)
                elif expected_type == "array" or expected_type == "list":
                    if isinstance(value, str):
                        coerced_args[key] = [v.strip() for v in value.split(",") if v.strip()]
                    elif isinstance(value, list):
                        coerced_args[key] = value
                    else:
                        return {}, f"Parameter '{key}' must be a list, got {type(value).__name__}."
                else:
                    coerced_args[key] = str(value)
            except (ValueError, TypeError):
                return {}, f"Failed to coerce parameter '{key}' with value '{value}' to type '{expected_type}'."

        return coerced_args, None


tool_schema_validator = ToolSchemaValidator()
