"""
JKAI ZENITH — GOVERNANCE DOMAIN: PROMOTION GATE
File: core/governance/promotion_gate.py

Deterministic Promotion Gate for Self-Improvement Proposals.
Validates learning proposals (Skills, Prompts, Policies) before promoting to registry.
NEVER allows mutation of MissionContract invariants or Constitutional boundaries.
"""

from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional


@dataclass
class LearningProposal:
    """Proposal generated by Self-Improvement Loop."""
    proposal_id: str
    target_registry: str                 # "skill" | "prompt" | "routing_policy" | "recovery_strategy"
    proposal_type: str                   # "ADD_SKILL" | "UPDATE_PROMPT" | "ADAPT_ROUTING"
    payload: Dict[str, Any] = field(default_factory=dict)
    confidence_score: float = 0.85
    provenance_evidence: List[str] = field(default_factory=list)


@dataclass
class PromotionResult:
    """Result emitted by PromotionGate."""
    approved: bool
    proposal_id: str
    reason: str


class PromotionGate:
    """Deterministic Gate for Self-Improvement Proposals."""

    def evaluate_proposal(self, proposal: LearningProposal) -> PromotionResult:
        # Rule 1: Confidence score must meet minimum threshold
        if proposal.confidence_score < 0.80:
            return PromotionResult(
                approved=False,
                proposal_id=proposal.proposal_id,
                reason=f"Confidence score {proposal.confidence_score} < min 0.80 threshold"
            )

        # Rule 2: Cannot attempt to mutate core constitution or security contracts
        payload_keys = str(proposal.payload).lower()
        forbidden_keywords = ["missioncontract", "executionlease", "security_policy", "hard_filter"]
        for kw in forbidden_keywords:
            if kw in payload_keys:
                return PromotionResult(
                    approved=False,
                    proposal_id=proposal.proposal_id,
                    reason=f"Forbidden keyword '{kw}' detected. Self-improvement cannot mutate core constitution."
                )

        return PromotionResult(
            approved=True,
            proposal_id=proposal.proposal_id,
            reason="Proposal validated cleanly by PromotionGate."
        )
